version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_delivery
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - mongodb_data:/data/db
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mongodb_data: